In [ ]:
import pandas as pd

In [2]:
data = pd.read_csv("all_matches_edit.csv")

In [3]:
data

        match_id  season  start_date  ...      bowler  runs_off_bat  extras
0         335982    2008  18-04-2008  ...     P Kumar             0       1
1         335982    2008  18-04-2008  ...     P Kumar             0       0
2         335982    2008  18-04-2008  ...     P Kumar             0       1
3         335982    2008  18-04-2008  ...     P Kumar             0       0
4         335982    2008  18-04-2008  ...     P Kumar             0       0
...          ...     ...         ...  ...         ...           ...     ...
194349   1254060    2021  11-04-2021  ...  AD Russell             0       0
194350   1254060    2021  11-04-2021  ...  AD Russell             1       0
194351   1254060    2021  11-04-2021  ...  AD Russell             1       0
194352   1254060    2021  11-04-2021  ...  AD Russell             1       0
194353   1254060    2021  11-04-2021  ...  AD Russell             6       0

[194354 rows x 13 columns]

In [5]:
ndata = data[ data['season']>=2015 ]
ndata = ndata.reset_index().drop(['index'],axis=1)
ndata

       match_id  season  start_date  ...      bowler  runs_off_bat  extras
0        829733    2015  18-04-2015  ...    UT Yadav             0       0
1        829733    2015  18-04-2015  ...    UT Yadav             0       0
2        829733    2015  18-04-2015  ...    UT Yadav             0       0
3        829733    2015  18-04-2015  ...    UT Yadav             0       0
4        829733    2015  18-04-2015  ...    UT Yadav             0       0
...         ...     ...         ...  ...         ...           ...     ...
85499   1254060    2021  11-04-2021  ...  AD Russell             0       0
85500   1254060    2021  11-04-2021  ...  AD Russell             1       0
85501   1254060    2021  11-04-2021  ...  AD Russell             1       0
85502   1254060    2021  11-04-2021  ...  AD Russell             1       0
85503   1254060    2021  11-04-2021  ...  AD Russell             6       0

[85504 rows x 13 columns]

In [6]:
ndata['season'].unique()

array([2015, 2016, 2017, 2019, 2018, 2020, 2021])

In [7]:
ndata['venue'].unique()

array(['Maharashtra Cricket Association Stadium',
       'Sardar Patel Stadium, Motera', 'M Chinnaswamy Stadium',
       'Feroz Shah Kotla',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Eden Gardens', 'MA Chidambaram Stadium, Chepauk',
       'Wankhede Stadium', 'Punjab Cricket Association Stadium, Mohali',
       'Rajiv Gandhi International Stadium, Uppal', 'Brabourne Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex',
       'Punjab Cricket Association IS Bindra Stadium, Mohali',
       'Saurashtra Cricket Association Stadium', 'Green Park',
       'M.Chinnaswamy Stadium', 'Holkar Cricket Stadium',
       'MA Chidambaram Stadium', 'Sawai Mansingh Stadium',
       'Arun Jaitley Stadium', 'Rajiv Gandhi International Stadium',
       'Punjab Cricket Association IS Bindra Stadium',
       'Sheikh Zayed Stadium', 'Dubai International Cricket Stadium',
       'Sharjah Cricket Stadium',
       'MA Chidambaram Stadium, Chepauk, Chennai',
       'Wankhede Stadium, Mumbai'], dtype=object)

In [10]:
for i in range(len(ndata['venue'])):
  if ndata['venue'][i]=='M.Chinnaswamy Stadium':
     ndata['venue'][i]='M Chinnaswamy Stadium'
  if ndata['venue'][i]=='MA Chidambaram Stadium, Chepauk, Chennai':
     ndata['venue'][i]='MA Chidambaram Stadium'
  if ndata['venue'][i]=='Wankhede Stadium, Mumbai':
     ndata['venue'][i]= 'Wankhede Stadium'
  if ndata['venue'][i]=='Rajiv Gandhi International Stadium, Uppal':
     ndata['venue'][i]= 'Rajiv Gandhi International Stadium'
  if ndata['venue'][i]=='MA Chidambaram Stadium, Chepauk':
     ndata['venue'][i]='MA Chidambaram Stadium'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

In [13]:
venues = ndata["venue"].unique()
pd.DataFrame(venues).to_csv("venues_pitchtype.csv")

In [14]:
ndata['batting_team'].unique()

array(['Kings XI Punjab', 'Kolkata Knight Riders', 'Chennai Super Kings',
       'Rajasthan Royals', 'Mumbai Indians',
       'Royal Challengers Bangalore', 'Delhi Daredevils',
       'Sunrisers Hyderabad', 'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals'], dtype=object)

In [48]:
dic={
    'match_id':[],
     'innings':[],
    'venue':[],
     'season':[],
     'batting_team':[],
     'bowling_team':[],
     'batsmen':[],
     'bolwers':[],
     'run':[]
}
input = pd.DataFrame(dic)
input

Empty DataFrame
Columns: [match_id, innings, venue, season, batting_team, bowling_team, batsmen, bolwers, run]
Index: []

In [49]:
for match in ndata["match_id"].unique():
  print(match)
  if match==829763:
    continue
  df = ndata[ndata['match_id']==match]
  
  #i1
  i1 = df[df['innings']==1]
  i1= i1.reset_index()
  dic['innings']=1
  dic['match_id']=match
  dic['venue']=i1['venue'][0]
  dic['season']=i1['season'][0]
  dic['batting_team']=i1['batting_team'][0]
  dic['bowling_team']=i1['bowling_team'][0]
  batsman = set()
  for bat in i1['striker'].unique():
    batsman.add(bat)
  for bat in i1['non_striker'].unique():
    batsman.add(bat)
  BM=""
  for bat in batsman:
    BM= BM + bat + ":"
  dic['batsmen']=BM
  bolwer=set()
  for bol in i1['bowler'].unique():
    bolwer.add(bol)
  B=''
  for bol in bolwer:
    B=B+bol+':'
  dic['bolwers']=B
  dic['run'] = i1[i1['ball']<6.0]['runs_off_bat'].sum()+i1[i1['ball']<6.0]['extras'].sum()

  input.loc[len(input)]=dic

  #i2
  i1 = df[df['innings']==2]
  i1=i1.reset_index()
  dic['innings']=2
  #dic['match_id']=match
  #dic['venue']=i1['venue'][0]
  #dic['season']=i1['season'][0]
  dic['batting_team']=i1['batting_team'][0]
  dic['bowling_team']=i1['bowling_team'][0]
  batsman = set()
  for bat in i1['striker'].unique():
    batsman.add(bat)
  for bat in i1['non_striker'].unique():
    batsman.add(bat)
  BM=""
  for bat in batsman:
    BM= BM + bat + ":"
  dic['batsmen']=BM
  bolwer=set()
  for bol in i1['bowler'].unique():
    bolwer.add(bol)
  B=''
  for bol in bolwer:
    B=B+bol+':'
  dic['bolwers']=B
  dic['run'] = i1[i1['ball']<6.0]['runs_off_bat'].sum()+i1[i1['ball']<6.0]['extras'].sum()

  input.loc[len(input)]=dic
  print(match)

829733
829733
829735
829735
829737
829737
829739
829739
829741
829741
829743
829743
829745
829745
829747
829747
829749
829749
829705
829705
829707
829707
829709
829709
829713
829713
829711
829711
829715
829715
829717
829717
829719
829719
829721
829721
829725
829725
829727
829727
829729
829729
829731
829731
829751
829751
829753
829753
829757
829757
829759
829759
829765
829765
829723
829723
829763
829767
829767
829769
829769
829771
829771
829773
829773
829775
829775
829777
829777
829779
829779
829781
829781
829783
829783
829785
829785
829787
829787
829761
829761
829789
829789
829791
829791
829793
829793
829795
829795
829797
829797
829799
829799
829801
829801
829803
829803
829805
829805
829807
829807
829809
829809
829811
829811
829813
829813
829815
829815
829817
829817
829819
829819
829821
829821
829823
829823
980901
980901
980903
980903
980905
980905
980907
980907
980909
980909
980911
980911
980913
980913
980915
980915
980917
980917
980919
980919
980921
980921
980923
980923
980925
980925
980927
980927
980929
980929
980931
980931
980933
980933
980935
980935
980937
980937
980939
980939
980941
980941
980943
980943
980945
980945
980947
980947
980949
980949
980951
980951
980953
980953
980955
980955
980957
980957
980959
980959
980961
980961
980963
980963
980965
980965
980967
980967
980969
980969
980971
980971
980973
980973
980975
980975
980977
980977
980979
980979
980981
980981
980983
980983
980985
980985
980987
980987
980989
980989
980991
980991
980993
980993
980995
980995
980997
980997
980999
980999
981001
981001
981003
981003
981005
981005
981007
981007
981009
981009
981011
981011
981013
981013
981015
981015
981017
981017
981019
981019
1082591
1082591
1082592
1082592
1082593
1082593
1082595
1082595
1082594
1082594
1082596
1082596
1082597
1082597
1082598
1082598
1082599
1082599
1082600
1082600
1082601
1082601
1082602
1082602
1082603
1082603
1082604
1082604
1082605
1082605
1082606
1082606
1082607
1082607
1082608
1082608
1082609
1082609
1082610
1082610
1082611
1082611
1082612
1082612
1082613
1082613
1082614
1082614
1082615
1082615
1082616
1082616
1082617
1082617
1082618
1082618
1082620
1082620
1082621
1082621
1082622
1082622
1082623
1082623
1082624
1082624
1082625
1082625
1082626
1082626
1082627
1082627
1082628
1082628
1082629
1082629
1082630
1082630
1082631
1082631
1082632
1082632
1082633
1082633
1082634
1082634
1082635
1082635
1082636
1082636
1082637
1082637
1082638
1082638
1082639
1082639
1082640
1082640
1082641
1082641
1082642
1082642
1082643
1082643
1082644
1082644
1082645
1082645
1082646
1082646
1082647
1082647
1082648
1082648
1082649
1082649
1082650
1082650
1175356
1175356
1175357
1175357
1175358
1175358
1175359
1175359
1175360
1175360
1175361
1175361
1175362
1175362
1175363
1175363
1175364
1175364
1175365
1175365
1175366
1175366
1175367
1175367
1175368
1175368
1175369
1175369
1175370
1175370
1175371
1175371
1175372
1175372
1178393
1178393
1178394
1178394
1178395
1178395
1178396
1178396
1178397
1178397
1178398
1178398
1178399
1178399
1178400
1178400
1178401
1178401
1178402
1178402
1178403
1178403
1178404
1178404
1178405
1178405
1178406
1178406
1178407
1178407
1178408
1178408
1136561
1136561
1136562
1136562
1136563
1136563
1136564
1136564
1136565
1136565
1136566
1136566
1136567
1136567
1136568
1136568
1136569
1136569
1136570
1136570
1136571
1136571
1136572
1136572
1136573
1136573
1136574
1136574
1136575
1136575
1136576
1136576
1136577
1136577
1136578
1136578
1136579
1136579
1136580
1136580
1136581
1136581
1136582
1136582
1136583
1136583
1136584
1136584
1136585
1136585
1136586
1136586
1136587
1136587
1136588
1136588
1136589
1136589
1136590
1136590
1136591
1136591
1136592
1136592
1136593
1136593
1136594
1136594
1136595
1136595
1136596
1136596
1136597
1136597
1136598
1136598
1136599
1136599
1136600
1136600
1136601
1136601
1136602
1136602
1136603
1136603
1136604
1136604
1136605
1136605
1136606
1136606
1136607
1136607
1136608
1136608
1136609
1136609
1136610
1136610
1136611
1136611
1136612
1136612
1136613
1136613
1136614
1136614
1136615
1136615
1136616
1136616
1136617
1136617
1136618
1136618
1136619
1136619
1136620
1136620
1178409
1178409
1178410
1178410
1178411
1178411
1178412
1178412
1178413
1178413
1178414
1178414
1178415
1178415
1178416
1178416
1178417
1178417
1178418
1178418
1178419
1178419
1178420
1178420
1178421
1178421
1178422
1178422
1178423
1178423
1178424
1178424
1178425
1178425
1178426
1178426
1178427
1178427
1178428
1178428
1178429
1178429
1178430
1178430
1178431
1178431
1181764
1181764
1181766
1181766
1181767
1181767
1181768
1181768
1216492
1216492
1216493
1216493
1216534
1216534
1216496
1216496
1216508
1216508
1216539
1216539
1216510
1216510
1216545
1216545
1216527
1216527
1216504
1216504
1216532
1216532
1216547
1216547
1216503
1216503
1216516
1216516
1216514
1216514
1216515
1216515
1216513
1216513
1216538
1216538
1216519
1216519
1216511
1216511
1216501
1216501
1216542
1216542
1216500
1216500
1216523
1216523
1216525
1216525
1216507
1216507
1216529
1216529
1216540
1216540
1216528
1216528
1216543
1216543
1216531
1216531
1216526
1216526
1216509
1216509
1216522
1216522
1216512
1216512
1216517
1216517
1216533
1216533
1216546
1216546
1216494
1216494
1216518
1216518
1216521
1216521
1216497
1216497
1216498
1216498
1216541
1216541
1216544
1216544
1216520
1216520
1216524
1216524
1216499
1216499
1216536
1216536
1216537
1216537
1216502
1216502
1216505
1216505
1216506
1216506
1216530
1216530
1216535
1216535
1216495
1216495
1237177
1237177
1237178
1237178
1237180
1237180
1237181
1237181
1254058
1254058
1254059
1254059
1254060
1254060

In [50]:
input

      match_id  ...   run
0     829733.0  ...  48.0
1     829733.0  ...  53.0
2     829735.0  ...  39.0
3     829735.0  ...  47.0
4     829737.0  ...  48.0
..         ...  ...   ...
715  1254058.0  ...  46.0
716  1254059.0  ...  33.0
717  1254059.0  ...  65.0
718  1254060.0  ...  50.0
719  1254060.0  ...  35.0

[720 rows x 9 columns]

In [43]:
ndata[ndata['match_id']==829763]

      match_id  season  start_date  ...      bowler  runs_off_bat  extras
6749    829763    2015  29-04-2015  ...  TG Southee             0       0
6750    829763    2015  29-04-2015  ...  TG Southee             4       0
6751    829763    2015  29-04-2015  ...  TG Southee             6       0
6752    829763    2015  29-04-2015  ...  TG Southee             0       0
6753    829763    2015  29-04-2015  ...  TG Southee             0       0
...        ...     ...         ...  ...         ...           ...     ...
6872    829763    2015  29-04-2015  ...  TG Southee             0       1
6873    829763    2015  29-04-2015  ...  TG Southee             2       0
6874    829763    2015  29-04-2015  ...  TG Southee             0       0
6875    829763    2015  29-04-2015  ...  TG Southee             2       0
6876    829763    2015  29-04-2015  ...  TG Southee             1       0

[128 rows x 13 columns]

In [51]:
input.to_csv('2015_to_2020_F_6_overs_input.csv')

In [ ]:
current_v = ['Wankhede Stadium', 'Eden Gardens','MA Chidambaram Stadium','M Chinnaswamy Stadium','Feroz Shah Kotla']

In [ ]:
sett = set()
for i in range(len(ndata)):
  if ndata['venue'][i] in current_v:
    sett.add(ndata['match_id'][i])

len(sett)

88

In [ ]:
ndata['match_id'].nunique()

242

In [ ]:
for v in current_v:
  df = ndata[ndata['venue']==v]
  df = df[df['ball']<6.0]
  summ=0
  i1 = df[df['innings']==1]
  #i2 = df[df['innings']==2]
  for match in df['match_id'].unique():
    
    summ= summ + i1[i1['match_id']==match]['runs_off_bat'].sum()
    summ=summ + i1[i1['match_id']==match]['extras'].sum()
  #print(df['match_id'].nunique())
  print(v,"-->",summ/i1['match_id'].nunique())

Wankhede Stadium --> 49.76
Eden Gardens --> 50.30434782608695
MA Chidambaram Stadium --> 41.63636363636363
M Chinnaswamy Stadium --> 44.95454545454545
Feroz Shah Kotla --> 53.857142857142854

In [ ]:
ndata['bowler'].nunique()

191

In [ ]:
ndata['striker'].nunique()

247

In [ ]:
import plotly.express as px
fig = px.sunburst(ndata, path=[ 'season','venue','innings' ,'bowler','batting_team','striker'], values='runs_off_bat',hover_data=['ball'])
plotly.offline.plot(fig, filename='aman.html')

'aman.html'

In [ ]:
import plotly.express as px
df = px.data.tips()
fig = px.sunburst(df, path=['day', 'time', 'sex'], values='total_bill')
fig.show()

In [ ]:
for player in ndata['striker'].unique():
  if player in dic.keys():
    pass
  else:
    add the value {player : {bolwing type:data2['bolwingtype']}}